//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Materials/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""a8924fe9-872d-48bd-9a5b-b41c02e3a49b"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""259b2619-9983-40b4-b744-a88491e53cfc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""d71c26ab-4604-4d29-a15e-ec0ee49a3860"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""46d2142f-aa4e-426d-a1d5-16c078ee241e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swap Left"",
                    ""type"": ""Button"",
                    ""id"": ""34be1260-e9fa-430f-9c55-431b1c12dd59"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swap Right"",
                    ""type"": ""Button"",
                    ""id"": ""d5362d22-4eea-4392-84b7-af786cdb641e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Character 1"",
                    ""type"": ""Button"",
                    ""id"": ""b72b2841-01b0-4384-bbe6-e7ac1d5f25be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Character 2"",
                    ""type"": ""Button"",
                    ""id"": ""ca2ffd64-972e-4b7b-b651-88aae89f30da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Character 3"",
                    ""type"": ""Button"",
                    ""id"": ""193dc85c-3eb9-41f8-8ca3-b0fae1ae5de8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Character 4"",
                    ""type"": ""Button"",
                    ""id"": ""f0fc40a1-b1d1-4590-8e8a-9cfe3423ee85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraZoomIn"",
                    ""type"": ""Button"",
                    ""id"": ""287972b1-be9c-462c-a178-be5a8a9b7550"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraZoomOut"",
                    ""type"": ""Button"",
                    ""id"": ""42a7ae04-9547-435d-a41a-e98b1a52af57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b0e6434d-94a4-4048-83c5-11d958eef7b3"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a5fc6e92-d14d-4b06-8d57-6ad19c62f77c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""33e5944b-5c07-43f2-b20d-7403d303a9f7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""82089761-e257-4bdf-aae8-47a6b82ad09f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ff069616-0390-432d-b919-b755696e7601"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e13489b9-7b3a-4def-9a7c-53857e42909a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8ad2c315-9bb2-47c8-8a10-bd06815ac4eb"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ec91e5d-6959-4529-8ee8-d9b5aeab7497"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecd8e3c7-3436-4614-af50-51a30a6d9576"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ea90580-3684-400e-bcbf-0266994dba19"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15bb0409-63f9-470d-9ce0-8a156f2d985e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38e1f97c-9484-4bb3-acd7-53d87d819edc"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b4830a8-8989-4905-8c44-0f5d516191b2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d12dfd6-59d4-482b-88a8-d5fa8c0d566b"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00205297-409b-4793-9b26-3c1cfee3d165"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9309afa-50a1-4961-a652-506034f49690"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22441c00-91c7-4753-a239-552ca7cda8b9"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8f65d41-f77a-450c-ba70-14af027fc28f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0a615e3-7a9e-4267-b06e-ac7adb02081d"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d07ec611-fa52-43e6-8a8c-e09fc893a2cf"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1328b4ce-0269-4d42-8503-fc218b3b705e"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b3c3153-844b-49dd-802f-9bb2c9f3c004"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbce9a8b-8dff-452b-aea3-2fd230d61440"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoomIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d1c4b0c-54d6-47a2-b7a0-b3750855933d"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoomIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfe7b96f-8607-47e6-8d2c-fe2cb9707347"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoomOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb6b18ed-f377-4ffc-957d-44879cdc790d"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoomOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_Movement = m_Default.FindAction("Movement", throwIfNotFound: true);
        m_Default_Jump = m_Default.FindAction("Jump", throwIfNotFound: true);
        m_Default_Interact = m_Default.FindAction("Interact", throwIfNotFound: true);
        m_Default_SwapLeft = m_Default.FindAction("Swap Left", throwIfNotFound: true);
        m_Default_SwapRight = m_Default.FindAction("Swap Right", throwIfNotFound: true);
        m_Default_SwitchCharacter1 = m_Default.FindAction("Switch Character 1", throwIfNotFound: true);
        m_Default_SwitchCharacter2 = m_Default.FindAction("Switch Character 2", throwIfNotFound: true);
        m_Default_SwitchCharacter3 = m_Default.FindAction("Switch Character 3", throwIfNotFound: true);
        m_Default_SwitchCharacter4 = m_Default.FindAction("Switch Character 4", throwIfNotFound: true);
        m_Default_CameraZoomIn = m_Default.FindAction("CameraZoomIn", throwIfNotFound: true);
        m_Default_CameraZoomOut = m_Default.FindAction("CameraZoomOut", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_Default_Movement;
    private readonly InputAction m_Default_Jump;
    private readonly InputAction m_Default_Interact;
    private readonly InputAction m_Default_SwapLeft;
    private readonly InputAction m_Default_SwapRight;
    private readonly InputAction m_Default_SwitchCharacter1;
    private readonly InputAction m_Default_SwitchCharacter2;
    private readonly InputAction m_Default_SwitchCharacter3;
    private readonly InputAction m_Default_SwitchCharacter4;
    private readonly InputAction m_Default_CameraZoomIn;
    private readonly InputAction m_Default_CameraZoomOut;
    public struct DefaultActions
    {
        private @Controls m_Wrapper;
        public DefaultActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Default_Movement;
        public InputAction @Jump => m_Wrapper.m_Default_Jump;
        public InputAction @Interact => m_Wrapper.m_Default_Interact;
        public InputAction @SwapLeft => m_Wrapper.m_Default_SwapLeft;
        public InputAction @SwapRight => m_Wrapper.m_Default_SwapRight;
        public InputAction @SwitchCharacter1 => m_Wrapper.m_Default_SwitchCharacter1;
        public InputAction @SwitchCharacter2 => m_Wrapper.m_Default_SwitchCharacter2;
        public InputAction @SwitchCharacter3 => m_Wrapper.m_Default_SwitchCharacter3;
        public InputAction @SwitchCharacter4 => m_Wrapper.m_Default_SwitchCharacter4;
        public InputAction @CameraZoomIn => m_Wrapper.m_Default_CameraZoomIn;
        public InputAction @CameraZoomOut => m_Wrapper.m_Default_CameraZoomOut;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @SwapLeft.started += instance.OnSwapLeft;
            @SwapLeft.performed += instance.OnSwapLeft;
            @SwapLeft.canceled += instance.OnSwapLeft;
            @SwapRight.started += instance.OnSwapRight;
            @SwapRight.performed += instance.OnSwapRight;
            @SwapRight.canceled += instance.OnSwapRight;
            @SwitchCharacter1.started += instance.OnSwitchCharacter1;
            @SwitchCharacter1.performed += instance.OnSwitchCharacter1;
            @SwitchCharacter1.canceled += instance.OnSwitchCharacter1;
            @SwitchCharacter2.started += instance.OnSwitchCharacter2;
            @SwitchCharacter2.performed += instance.OnSwitchCharacter2;
            @SwitchCharacter2.canceled += instance.OnSwitchCharacter2;
            @SwitchCharacter3.started += instance.OnSwitchCharacter3;
            @SwitchCharacter3.performed += instance.OnSwitchCharacter3;
            @SwitchCharacter3.canceled += instance.OnSwitchCharacter3;
            @SwitchCharacter4.started += instance.OnSwitchCharacter4;
            @SwitchCharacter4.performed += instance.OnSwitchCharacter4;
            @SwitchCharacter4.canceled += instance.OnSwitchCharacter4;
            @CameraZoomIn.started += instance.OnCameraZoomIn;
            @CameraZoomIn.performed += instance.OnCameraZoomIn;
            @CameraZoomIn.canceled += instance.OnCameraZoomIn;
            @CameraZoomOut.started += instance.OnCameraZoomOut;
            @CameraZoomOut.performed += instance.OnCameraZoomOut;
            @CameraZoomOut.canceled += instance.OnCameraZoomOut;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @SwapLeft.started -= instance.OnSwapLeft;
            @SwapLeft.performed -= instance.OnSwapLeft;
            @SwapLeft.canceled -= instance.OnSwapLeft;
            @SwapRight.started -= instance.OnSwapRight;
            @SwapRight.performed -= instance.OnSwapRight;
            @SwapRight.canceled -= instance.OnSwapRight;
            @SwitchCharacter1.started -= instance.OnSwitchCharacter1;
            @SwitchCharacter1.performed -= instance.OnSwitchCharacter1;
            @SwitchCharacter1.canceled -= instance.OnSwitchCharacter1;
            @SwitchCharacter2.started -= instance.OnSwitchCharacter2;
            @SwitchCharacter2.performed -= instance.OnSwitchCharacter2;
            @SwitchCharacter2.canceled -= instance.OnSwitchCharacter2;
            @SwitchCharacter3.started -= instance.OnSwitchCharacter3;
            @SwitchCharacter3.performed -= instance.OnSwitchCharacter3;
            @SwitchCharacter3.canceled -= instance.OnSwitchCharacter3;
            @SwitchCharacter4.started -= instance.OnSwitchCharacter4;
            @SwitchCharacter4.performed -= instance.OnSwitchCharacter4;
            @SwitchCharacter4.canceled -= instance.OnSwitchCharacter4;
            @CameraZoomIn.started -= instance.OnCameraZoomIn;
            @CameraZoomIn.performed -= instance.OnCameraZoomIn;
            @CameraZoomIn.canceled -= instance.OnCameraZoomIn;
            @CameraZoomOut.started -= instance.OnCameraZoomOut;
            @CameraZoomOut.performed -= instance.OnCameraZoomOut;
            @CameraZoomOut.canceled -= instance.OnCameraZoomOut;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnSwapLeft(InputAction.CallbackContext context);
        void OnSwapRight(InputAction.CallbackContext context);
        void OnSwitchCharacter1(InputAction.CallbackContext context);
        void OnSwitchCharacter2(InputAction.CallbackContext context);
        void OnSwitchCharacter3(InputAction.CallbackContext context);
        void OnSwitchCharacter4(InputAction.CallbackContext context);
        void OnCameraZoomIn(InputAction.CallbackContext context);
        void OnCameraZoomOut(InputAction.CallbackContext context);
    }
}
